# Generated by Django 4.2 on 2024-10-08 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='дата'),
        ),
        migrations.AddField(
            model_name='entry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
