# Generated by Django 4.2 on 2024-10-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_entry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date',
        ),
        migrations.AddField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='entry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата последнего изменения'),
        ),
    ]
